NFL_TEAMS = {"JAX" : "Jacksonville Jaguars",
             "CLE" : "Cleveland Browns",
             "BUF" : "Buffalo Bills",
             "WAS" : "Washington Commanders",
             "DET" : "Detroit Lions",
             "ATL" : "Atlanta Falcons",
             "PIT" : "Pittsburgh Steelers",
             "ARI" : "Arizona Cardinals",
             "GB" : "Green Bay Packers",
             "LAC" : "Los Angeles Chargers",
             "MIA" : "Miami Dolphins",
             "SF" : "San Francisco 49ers",
             "NYG" : "New York Giants",
             "DAL" : "Dallas Cowboys",
             "PHI" : "Philadelphia Eagles",
             "CAR" : "Carolina Panthers",
             "LAR" : "Los Angelas Rams",
             "MIN" : "Minnesota Vikings",
             "NO" : "New Orleans Saints",
             "SEA" : "Seattle Seahawks",
             "TB" : "Tampa Bay Buccaneers",
             "BAL" : "Baltimore Ravens",
             "CIN" : "Cincinnati Bengals",
             "DEN" : "Denver Broncos",
             "HOU" : "Houston Texans",
             "IND" : "Indianapolis Colts",   
             "KC" : "Kansas City Chiefs",
             "LVR" : "Las Vegas Raiders",
             "NE" : "New England Patriots",
             "NYJ" : "New York Jets",
             "TEN" : "Tennessee Titans",
             "CHI" : "Chicago Bears",
             "JAGUARS" : "Jacksonville Jaguars",
             "BROWNS" : "Cleveland Browns",
             "BILLS" : "Buffalo Bills",
             "COMMANDERS" : "Washington Commanders",
             "LIONS" : "Detroit Lions",
             "FALCONS" : "Atlanta Falcons",
             "STEELERS" : "Pittsburgh Steelers",
             "CARDINALS" : "Arizona Cardinals",
             "PACKERS" : "Green Bay Packers",
             "CHARGERS" : "Los Angeles Chargers",
             "DOLPHINS" : "Miami Dolphins",
             "49ERS" : "San Francisco 49ers",
             "GIANTS" : "New York Giants",
             "COWBOYS" : "Dallas Cowboys",
             "EAGLES" : "Philadelphia Eagles",
             "PANTHERS" : "Carolina Panthers",
             "RAMS" : "Los Angelas Rams",
             "VIKINGS" : "Minnesota Vikings",
             "SAINTS" : "New Orleans Saints",
             "SEAHAWKS" : "Seattle Seahawks",
             "BUCCANEERS" : "Tampa Bay Buccaneers",
             "RAVENS" : "Baltimore Ravens",
             "BENGALS" : "Cincinnati Bengals",
             "BRONCOS" : "Denver Broncos",
             "TEXANS" : "Houston Texans",
             "COLTS" : "Indianapolis Colts",   
             "CHIEFS" : "Kansas City Chiefs",
             "RAIDERS" : "Las Vegas Raiders",
             "PATRIOTS" : "New England Patriots",
             "JETS" : "New York Jets",
             "TITANS" : "Tennessee Titans",
             "BEARS" : "Chicago Bears",
             }

def change_name(name):
    if name.upper() in NFL_TEAMS:
        new_name = NFL_TEAMS[name.upper()]
        return new_name
    else:
        return name